#define limitNO   22
#define limitNC   23
#define M2START   15
#define pbREV     20
#define pbFWD     21
#define EMERGENCY 3
#define pbSTART   18
#define pbSTOP    19
#define pbRST     2
#define PWM       A0
#define ledSTART  29
#define ledSTOP   28
#define ledDIS    27
#define ledEN     26
#define ledON     25
#define ledM2ON   24
#define ledM2OFF  31     
#define m1ON      14
#define mPWM      5
#define m2RIGHT   4
#define m2LEFT    6
#define BUZZER    30
